// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package foo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IAuth struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IAuth) Reset()         { *m = IAuth{} }
func (m *IAuth) String() string { return proto.CompactTextString(m) }
func (*IAuth) ProtoMessage()    {}
func (*IAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *IAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IAuth.Unmarshal(m, b)
}
func (m *IAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IAuth.Marshal(b, m, deterministic)
}
func (m *IAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IAuth.Merge(m, src)
}
func (m *IAuth) XXX_Size() int {
	return xxx_messageInfo_IAuth.Size(m)
}
func (m *IAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_IAuth.DiscardUnknown(m)
}

var xxx_messageInfo_IAuth proto.InternalMessageInfo

func (m *IAuth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *IAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthLoginPayload struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLoginPayload) Reset()         { *m = AuthLoginPayload{} }
func (m *AuthLoginPayload) String() string { return proto.CompactTextString(m) }
func (*AuthLoginPayload) ProtoMessage()    {}
func (*AuthLoginPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *AuthLoginPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginPayload.Unmarshal(m, b)
}
func (m *AuthLoginPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginPayload.Marshal(b, m, deterministic)
}
func (m *AuthLoginPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginPayload.Merge(m, src)
}
func (m *AuthLoginPayload) XXX_Size() int {
	return xxx_messageInfo_AuthLoginPayload.Size(m)
}
func (m *AuthLoginPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginPayload proto.InternalMessageInfo

func (m *AuthLoginPayload) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthLoginPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LoginResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*IAuth)(nil), "auth.IAuth")
	proto.RegisterType((*AuthLoginPayload)(nil), "auth.AuthLoginPayload")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
}

func init() {
	proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2)
}

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x62, 0x94, 0x66, 0x52, 0xb5, 0x8c, 0x20, 0x25, 0x27, 0xdd, 0x93, 0xa7, 0x16, 0x14,
	0x2f, 0xde, 0xec, 0x4d, 0xf1, 0x20, 0xd1, 0x93, 0x17, 0x59, 0xdb, 0xb1, 0x2d, 0xd1, 0x4c, 0xc8,
	0x6c, 0x90, 0xfe, 0xbd, 0xec, 0x6c, 0x5b, 0x68, 0x40, 0x2f, 0xbb, 0xf3, 0xde, 0x0c, 0xef, 0xcd,
	0xbe, 0x85, 0x53, 0xdb, 0xba, 0xe5, 0xc4, 0x1f, 0xe3, 0xba, 0x61, 0xc7, 0x98, 0xf8, 0xda, 0xbc,
	0xc0, 0xe1, 0xc3, 0x7d, 0xeb, 0x96, 0x88, 0x90, 0x54, 0xf6, 0x9b, 0x46, 0xd1, 0x45, 0x74, 0x95,
	0x16, 0x5a, 0x63, 0x0e, 0xfd, 0x56, 0xa8, 0x51, 0x3e, 0x56, 0x7e, 0x87, 0x7d, 0xaf, 0xb6, 0x22,
	0x3f, 0xdc, 0xcc, 0x47, 0x07, 0xa1, 0xb7, 0xc5, 0xe6, 0x11, 0x86, 0x5e, 0xf3, 0x89, 0x17, 0xab,
	0xea, 0xd9, 0xae, 0xbf, 0xd8, 0xce, 0xf7, 0xb4, 0xa2, 0x7f, 0xb4, 0xe2, 0x8e, 0x96, 0x81, 0x61,
	0x41, 0x8b, 0x95, 0x38, 0x6a, 0x0a, 0x92, 0x9a, 0x2b, 0x21, 0x3c, 0x81, 0x98, 0x4b, 0x55, 0xe9,
	0x17, 0x31, 0x97, 0x66, 0x0a, 0xc7, 0xea, 0xf5, 0xd7, 0x00, 0x5e, 0xc2, 0xc0, 0xce, 0x66, 0x24,
	0xf2, 0xee, 0xb8, 0xa4, 0x6a, 0x63, 0x92, 0x05, 0xee, 0xd5, 0x53, 0xd7, 0x6b, 0x48, 0x34, 0x87,
	0x5b, 0x18, 0xf8, 0x7b, 0xeb, 0x89, 0xd9, 0x58, 0x33, 0xd3, 0x90, 0xf2, 0xf3, 0x00, 0xba, 0x0b,
	0x99, 0x1e, 0xde, 0x41, 0xba, 0x7b, 0x32, 0x6e, 0xc6, 0xba, 0x19, 0xe4, 0x67, 0x81, 0xdf, 0xdb,
	0xd5, 0xf4, 0xa6, 0xd9, 0x5b, 0xaa, 0x5f, 0x32, 0xf9, 0x64, 0xfe, 0x38, 0xd2, 0xf2, 0xe6, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0x5e, 0x2b, 0x21, 0xb0, 0x01, 0x00, 0x00,
}
