// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserCreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserCreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserUpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateRequest) Reset()         { *m = UserUpdateRequest{} }
func (m *UserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UserUpdateRequest) ProtoMessage()    {}
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *UserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateRequest.Unmarshal(m, b)
}
func (m *UserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateRequest.Merge(m, src)
}
func (m *UserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UserUpdateRequest.Size(m)
}
func (m *UserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateRequest proto.InternalMessageInfo

func (m *UserUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserUpdateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserByIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByIDRequest) Reset()         { *m = UserByIDRequest{} }
func (m *UserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UserByIDRequest) ProtoMessage()    {}
func (*UserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *UserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByIDRequest.Unmarshal(m, b)
}
func (m *UserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByIDRequest.Marshal(b, m, deterministic)
}
func (m *UserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByIDRequest.Merge(m, src)
}
func (m *UserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UserByIDRequest.Size(m)
}
func (m *UserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByIDRequest proto.InternalMessageInfo

func (m *UserByIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserListQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListQuery) Reset()         { *m = UserListQuery{} }
func (m *UserListQuery) String() string { return proto.CompactTextString(m) }
func (*UserListQuery) ProtoMessage()    {}
func (*UserListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{5}
}

func (m *UserListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListQuery.Unmarshal(m, b)
}
func (m *UserListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListQuery.Marshal(b, m, deterministic)
}
func (m *UserListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListQuery.Merge(m, src)
}
func (m *UserListQuery) XXX_Size() int {
	return xxx_messageInfo_UserListQuery.Size(m)
}
func (m *UserListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_UserListQuery proto.InternalMessageInfo

type UserDeleteResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteResponse) Reset()         { *m = UserDeleteResponse{} }
func (m *UserDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*UserDeleteResponse) ProtoMessage()    {}
func (*UserDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{6}
}

func (m *UserDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteResponse.Unmarshal(m, b)
}
func (m *UserDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteResponse.Marshal(b, m, deterministic)
}
func (m *UserDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteResponse.Merge(m, src)
}
func (m *UserDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_UserDeleteResponse.Size(m)
}
func (m *UserDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteResponse proto.InternalMessageInfo

func (m *UserDeleteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCreateRequest)(nil), "foo.UserCreateRequest")
	proto.RegisterType((*UserUpdateRequest)(nil), "foo.UserUpdateRequest")
	proto.RegisterType((*UserByIDRequest)(nil), "foo.UserByIDRequest")
	proto.RegisterType((*User)(nil), "foo.User")
	proto.RegisterType((*Users)(nil), "foo.Users")
	proto.RegisterType((*UserListQuery)(nil), "foo.UserListQuery")
	proto.RegisterType((*UserDeleteResponse)(nil), "foo.UserDeleteResponse")
}

func init() {
	proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74)
}

var fileDescriptor_ed89022014131a74 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x61, 0x1b, 0x20, 0x0f, 0x95, 0xd8, 0x18, 0x5d, 0x48, 0x8c, 0xd8, 0x13, 0x07, 0x33,
	0x22, 0x9e, 0x3d, 0x80, 0x24, 0xc6, 0xc4, 0x8b, 0x23, 0x5c, 0xbc, 0x90, 0xc9, 0x1e, 0x66, 0x89,
	0xd0, 0xd9, 0x76, 0x1a, 0x3e, 0x86, 0x9f, 0xc1, 0x2f, 0x6a, 0xda, 0x6e, 0x75, 0x33, 0xc1, 0x83,
	0x97, 0xa5, 0xef, 0xff, 0xeb, 0x7b, 0xff, 0xee, 0xf5, 0x15, 0xba, 0x99, 0x40, 0x3e, 0x54, 0x9f,
	0x20, 0xe5, 0x4c, 0x32, 0xe2, 0xae, 0x18, 0xa3, 0x0b, 0x38, 0x9a, 0x0b, 0xe4, 0xb7, 0x1c, 0x23,
	0x89, 0x21, 0xbe, 0x65, 0x28, 0x24, 0x21, 0xe0, 0x6d, 0xa2, 0x35, 0xfa, 0xf5, 0x7e, 0x7d, 0xd0,
	0x0e, 0xf5, 0x9a, 0xf4, 0x60, 0x4f, 0xe5, 0x6a, 0xdd, 0xd1, 0xba, 0x8d, 0x15, 0x4b, 0x23, 0x21,
	0x3e, 0x18, 0x8f, 0x7d, 0xd7, 0xb0, 0x22, 0xa6, 0x33, 0x63, 0x30, 0x4f, 0xe3, 0x92, 0xc1, 0x21,
	0x38, 0x49, 0xac, 0xcb, 0xbb, 0xa1, 0x93, 0xc4, 0xd6, 0xd0, 0xd9, 0x61, 0xe8, 0x56, 0x0d, 0xe9,
	0x05, 0x74, 0x55, 0xd1, 0xc9, 0xf6, 0x7e, 0xba, 0xa3, 0x24, 0xfd, 0xaa, 0x83, 0xa7, 0xf6, 0x94,
	0x80, 0xf7, 0x1f, 0x2f, 0x72, 0x06, 0xb0, 0xd4, 0xdd, 0x89, 0x17, 0x91, 0xf4, 0x3d, 0x4d, 0xdb,
	0xb9, 0x32, 0x96, 0x0a, 0x67, 0xfa, 0xdf, 0x34, 0x6e, 0x18, 0x9c, 0x2b, 0x06, 0xc7, 0xf8, 0x8a,
	0x39, 0x6e, 0x1a, 0x9c, 0x2b, 0x63, 0x49, 0x07, 0xd0, 0x50, 0x87, 0x14, 0xe4, 0x1c, 0x1a, 0xca,
	0x51, 0xf8, 0x5e, 0xdf, 0x1d, 0x74, 0x46, 0xed, 0x60, 0xc5, 0x58, 0xa0, 0x50, 0x68, 0x74, 0xda,
	0x85, 0x03, 0x15, 0x3e, 0x24, 0x42, 0x3e, 0x66, 0xc8, 0xb7, 0x34, 0x00, 0xa2, 0x84, 0xa9, 0xae,
	0x15, 0xa2, 0x48, 0xd9, 0x46, 0x20, 0xf1, 0xa1, 0xb5, 0x46, 0x21, 0xa2, 0x97, 0xe2, 0xf6, 0x8a,
	0x70, 0xf4, 0xe9, 0x40, 0x47, 0x25, 0xcc, 0x90, 0xbf, 0x27, 0x4b, 0x24, 0x43, 0xe8, 0xdc, 0xa1,
	0x2c, 0x6a, 0x12, 0x62, 0x1d, 0xad, 0x45, 0x0f, 0xac, 0x26, 0x68, 0x8d, 0x5c, 0x01, 0x98, 0x31,
	0xd1, 0x6d, 0x3d, 0xb1, 0xac, 0x32, 0x3b, 0xbd, 0x9f, 0x93, 0x9b, 0x14, 0x73, 0xf1, 0xbf, 0x52,
	0x2a, 0xd3, 0x50, 0x4d, 0xb9, 0x84, 0x56, 0x7e, 0x2c, 0x72, 0x6c, 0xf5, 0xd2, 0x45, 0x57, 0x77,
	0xdf, 0x00, 0x98, 0x06, 0xfc, 0x91, 0x70, 0x6a, 0xd5, 0x6a, 0xaf, 0x68, 0x6d, 0xb2, 0xff, 0x04,
	0xfa, 0x2d, 0xe8, 0x67, 0xf1, 0xdc, 0xd4, 0xeb, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c,
	0x83, 0x6b, 0x56, 0x2a, 0x03, 0x00, 0x00,
}
