// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookListQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookListQuery) Reset()         { *m = BookListQuery{} }
func (m *BookListQuery) String() string { return proto.CompactTextString(m) }
func (*BookListQuery) ProtoMessage()    {}
func (*BookListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *BookListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookListQuery.Unmarshal(m, b)
}
func (m *BookListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookListQuery.Marshal(b, m, deterministic)
}
func (m *BookListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookListQuery.Merge(m, src)
}
func (m *BookListQuery) XXX_Size() int {
	return xxx_messageInfo_BookListQuery.Size(m)
}
func (m *BookListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BookListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BookListQuery proto.InternalMessageInfo

type BookResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookResponse) Reset()         { *m = BookResponse{} }
func (m *BookResponse) String() string { return proto.CompactTextString(m) }
func (*BookResponse) ProtoMessage()    {}
func (*BookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *BookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookResponse.Unmarshal(m, b)
}
func (m *BookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookResponse.Marshal(b, m, deterministic)
}
func (m *BookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookResponse.Merge(m, src)
}
func (m *BookResponse) XXX_Size() int {
	return xxx_messageInfo_BookResponse.Size(m)
}
func (m *BookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookResponse proto.InternalMessageInfo

func (m *BookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BookCreateRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCreateRequest) Reset()         { *m = BookCreateRequest{} }
func (m *BookCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BookCreateRequest) ProtoMessage()    {}
func (*BookCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *BookCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCreateRequest.Unmarshal(m, b)
}
func (m *BookCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCreateRequest.Marshal(b, m, deterministic)
}
func (m *BookCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCreateRequest.Merge(m, src)
}
func (m *BookCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BookCreateRequest.Size(m)
}
func (m *BookCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookCreateRequest proto.InternalMessageInfo

func (m *BookCreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookCreateRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type BookUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookUpdateRequest) Reset()         { *m = BookUpdateRequest{} }
func (m *BookUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*BookUpdateRequest) ProtoMessage()    {}
func (*BookUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *BookUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookUpdateRequest.Unmarshal(m, b)
}
func (m *BookUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookUpdateRequest.Marshal(b, m, deterministic)
}
func (m *BookUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookUpdateRequest.Merge(m, src)
}
func (m *BookUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_BookUpdateRequest.Size(m)
}
func (m *BookUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookUpdateRequest proto.InternalMessageInfo

func (m *BookUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BookUpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookUpdateRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type BookByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookByIdRequest) Reset()         { *m = BookByIdRequest{} }
func (m *BookByIdRequest) String() string { return proto.CompactTextString(m) }
func (*BookByIdRequest) ProtoMessage()    {}
func (*BookByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *BookByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookByIdRequest.Unmarshal(m, b)
}
func (m *BookByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookByIdRequest.Marshal(b, m, deterministic)
}
func (m *BookByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookByIdRequest.Merge(m, src)
}
func (m *BookByIdRequest) XXX_Size() int {
	return xxx_messageInfo_BookByIdRequest.Size(m)
}
func (m *BookByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookByIdRequest proto.InternalMessageInfo

func (m *BookByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{5}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Book) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Book) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*BookListQuery)(nil), "proto_bank.BookListQuery")
	proto.RegisterType((*BookResponse)(nil), "proto_bank.BookResponse")
	proto.RegisterType((*BookCreateRequest)(nil), "proto_bank.BookCreateRequest")
	proto.RegisterType((*BookUpdateRequest)(nil), "proto_bank.BookUpdateRequest")
	proto.RegisterType((*BookByIdRequest)(nil), "proto_bank.BookByIdRequest")
	proto.RegisterType((*Book)(nil), "proto_bank.Book")
}

func init() {
	proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8)
}

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x9f, 0xe6, 0xe9, 0x0b, 0x1d, 0xab, 0xd5, 0x45, 0x24, 0x56, 0x0a, 0xba, 0xa7, 0x9e,
	0x2a, 0xe8, 0xc5, 0x93, 0xd0, 0x58, 0x29, 0x05, 0x2f, 0x0d, 0x78, 0xf1, 0x52, 0x12, 0x77, 0xd0,
	0x90, 0xda, 0x8d, 0xd9, 0xcd, 0x21, 0x1f, 0xc7, 0xaf, 0xe5, 0xa7, 0x91, 0x7d, 0x09, 0x6d, 0x42,
	0xcc, 0xc5, 0x53, 0x32, 0xf3, 0x9f, 0xf9, 0xed, 0xce, 0xfe, 0x77, 0x01, 0x42, 0xce, 0xe3, 0x69,
	0x92, 0x72, 0xc9, 0x09, 0xe8, 0xcf, 0x3a, 0x0c, 0xb6, 0x31, 0x1d, 0xc2, 0xa1, 0xc7, 0x79, 0xfc,
	0x14, 0x09, 0xb9, 0xca, 0x30, 0xcd, 0xe9, 0x04, 0x06, 0x2a, 0xe1, 0xa3, 0x48, 0xf8, 0x56, 0x20,
	0x71, 0xa1, 0xf7, 0x81, 0x42, 0x04, 0x6f, 0xe8, 0xb6, 0x2e, 0x5b, 0x93, 0xbe, 0x5f, 0x84, 0x74,
	0x06, 0x27, 0xaa, 0xf2, 0x21, 0xc5, 0x40, 0xa2, 0x8f, 0x9f, 0x19, 0x0a, 0x49, 0x4e, 0xa1, 0x23,
	0x23, 0xb9, 0x29, 0x8a, 0x4d, 0x40, 0xce, 0xa0, 0x1b, 0x64, 0xf2, 0x9d, 0xa7, 0xae, 0xa3, 0xd3,
	0x36, 0xa2, 0x2b, 0x83, 0x78, 0x4e, 0xd8, 0x1e, 0xe2, 0x08, 0x9c, 0x88, 0xd9, 0x7e, 0x27, 0x62,
	0x3b, 0xa4, 0x53, 0x8f, 0xfc, 0x5f, 0x42, 0x5e, 0xc1, 0x50, 0x21, 0xbd, 0x7c, 0xc9, 0x7e, 0x01,
	0xd2, 0xaf, 0x16, 0xb4, 0x55, 0xcd, 0xdf, 0x56, 0x22, 0x63, 0x80, 0x57, 0x3d, 0x3b, 0x5b, 0x07,
	0xd2, 0x6d, 0x6b, 0xad, 0x6f, 0x33, 0x33, 0xa9, 0xe4, 0x4c, 0xcf, 0xa5, 0xe5, 0x8e, 0x91, 0x6d,
	0xc6, 0xc8, 0x0c, 0x37, 0x68, 0xe5, 0xae, 0x91, 0x6d, 0x66, 0x26, 0x6f, 0xbe, 0x1d, 0xe8, 0xa8,
	0x3d, 0x0a, 0x72, 0x07, 0xbd, 0x05, 0x4a, 0xbd, 0xdf, 0xf3, 0xe9, 0xce, 0xb9, 0x69, 0xc9, 0xb6,
	0xd1, 0x71, 0x55, 0xa2, 0xff, 0xc8, 0x3d, 0x1c, 0xd8, 0x4e, 0x2f, 0x5f, 0xce, 0xc9, 0x45, 0xb5,
	0x64, 0xef, 0x8c, 0x6a, 0xfb, 0x17, 0x00, 0xc6, 0x5c, 0xbd, 0xf8, 0xb8, 0x5a, 0x51, 0x32, 0x7e,
	0xe4, 0x56, 0xe5, 0xe2, 0x06, 0x19, 0x90, 0xb1, 0xb8, 0x1e, 0x54, 0xb2, 0xbf, 0x11, 0xf4, 0x08,
	0x30, 0xd7, 0x47, 0xa4, 0x41, 0x8d, 0x03, 0x35, 0x60, 0xbc, 0xc1, 0x8b, 0x79, 0x02, 0xd7, 0xea,
	0x51, 0x84, 0x5d, 0xfd, 0x7f, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xdc, 0x98, 0x94, 0x23,
	0x03, 0x00, 0x00,
}
